# Generated by Django 5.2 on 2025-05-04 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Vacancy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=100, verbose_name="название вакансии"
                    ),
                ),
                (
                    "short_description",
                    models.TextField(
                        max_length=100, verbose_name="краткое описание"
                    ),
                ),
                ("description", models.TextField(verbose_name="описание")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="активна"),
                ),
                (
                    "minimal_salary",
                    models.PositiveIntegerField(
                        null=True, verbose_name="зарплат от"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="дата создания"
                    ),
                ),
            ],
            options={
                "verbose_name": "вакансия",
                "verbose_name_plural": "вакансии",
            },
        ),
    ]
