# Generated by Django 5.2 on 2025-04-22 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, verbose_name="название"),
                ),
                ("slug", models.SlugField(verbose_name="слаг")),
            ],
            options={
                "verbose_name": "категория",
                "verbose_name_plural": "категории",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="название"),
                ),
                ("description", models.TextField(verbose_name="описание")),
                (
                    "count",
                    models.PositiveIntegerField(verbose_name="количество"),
                ),
                ("price", models.PositiveIntegerField(verbose_name="цена")),
                (
                    "image",
                    models.ImageField(upload_to="", verbose_name="фото"),
                ),
                (
                    "slug",
                    models.SlugField(max_length=100, verbose_name="слаг"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.category",
                        verbose_name="категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "товар",
                "verbose_name_plural": "товары",
            },
        ),
    ]
